export const personSchema = {
  "@context": "https://schema.org",
  "@type": "Person",
  name: "David Recalde",
  alternateName: "David García Recalde",
  jobTitle: "Cultural Industries & Communication Consultant",
  url: "https://davidrecalde.com",
  knowsAbout: [
    "Cultural Industries",
    "Soft Power",
    "Japan–Europe Cooperation",
    "Digital Communication",
    "Branding",
    "Research through Design",
    "Product Design",
    "Spain–Japan Projects",
    "SEO",
    "Cultural Platforms",
  ],
  sameAs: [
    "https://www.linkedin.com/in/davidgarciarecalde/",
    "https://noda.tokyo/",
    "https://supein.club/about-us/team/david-recalde/",
    "https://www.instagram.com/davidrecalde/",
    "https://www.softpower.school/",
  ],
  worksFor: {
    "@type": "Organization",
    name: "NODA.Tokyo",
    url: "https://noda.tokyo",
  },
  knowsLanguage: ["Spanish", "Japanese", "English"],
  address: {
    "@type": "PostalAddress",
    addressLocality: "Tokyo",
    addressCountry: "JP",
  },
};
